name: mobile_cloud_image_analytics
description: 모바일/클라우드 이미지 분석 기술 확보 PoC
author: June-Young Ahn <jyoungahn@gmail.com>

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'com.samsungfire.vision' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_mobile_vision: ^0.1.4+1
  # imei_plugin: ^1.2.0
  # serial_number: ^0.1.0

  # Gets phone number, carrier and device information.
  mobile_number:
  sim_info:
  device_info: ^0.4.2+7
  geolocator: ^6.0.0

  # Provides tools to work with the cameras on the device.
  # Caution: camera 패키지가 있을 때, moblie_number, sim_info, device_info 를 사용한 값이 null!!!
  # camera: ^0.5.8+6

  # Finds the correct paths to store images.
  # path_provider:

  # Creates paths that work on any platform.
  # path:

  # image_picker:

  # permission_handler: ^5.0.1+1

  # Provider pattern
  provider:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: FIRACODE
      fonts:
        - asset: assets/fonts/FIRACODE-BOLD.TTF
        - asset: assets/fonts/FIRACODE-LIGHT.TTF
        - asset: assets/fonts/FIRACODE-MEDIUM.TTF
        - asset: assets/fonts/FIRACODE-REGULAR.TTF
        - asset: assets/fonts/FIRACODE-SEMIBOLD.TTF
    - family: NANUMGOTHIC
      fonts:
        - asset: assets/fonts/NANUMGOTHIC.TTF
        - asset: assets/fonts/NANUMGOTHICBOLD.TTF
        - asset: assets/fonts/NANUMGOTHICEXTRABOLD.TTF
    - family: NANUMMYEONGJO
      fonts:
        - asset: assets/fonts/NANUMMYEONGJO.TTF
        - asset: assets/fonts/NANUMMYEONGJOBOLD.TTF
        - asset: assets/fonts/NANUMMYEONGJOEXTRABOLD.TTF