name: mobile_cloud_image_analytics
description: 모바일/클라우드 이미지 분석 기술 확보 PoC
author: June-Young Ahn <jyoungahn@gmail.com>

publish_to: 'com.samsungfire.vision'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Gets phone number, carrier and device information.
  mobile_number:
  sim_info:
  device_info: ^0.4.2+7
  geolocator: ^6.0.0

  # Camera control
  camera:
  path_provider:
  path:

  # Provider pattern
  provider:

  # API Call: http request & response
  http:

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
#  adaptive_icon_background: "assets/launcher/background.png"
#  adaptive_icon_foreground: "assets/launcher/foreground.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: FIRACODE
      fonts:
        - asset: assets/fonts/FIRACODE-BOLD.TTF
        - asset: assets/fonts/FIRACODE-LIGHT.TTF
        - asset: assets/fonts/FIRACODE-MEDIUM.TTF
        - asset: assets/fonts/FIRACODE-REGULAR.TTF
        - asset: assets/fonts/FIRACODE-SEMIBOLD.TTF
    - family: NANUMGOTHIC
      fonts:
        - asset: assets/fonts/NANUMGOTHIC.TTF
        - asset: assets/fonts/NANUMGOTHICBOLD.TTF
        - asset: assets/fonts/NANUMGOTHICEXTRABOLD.TTF
    - family: NANUMMYEONGJO
      fonts:
        - asset: assets/fonts/NANUMMYEONGJO.TTF
        - asset: assets/fonts/NANUMMYEONGJOBOLD.TTF
        - asset: assets/fonts/NANUMMYEONGJOEXTRABOLD.TTF