@endpoint=https://https://sfmi-vision.cognitiveservices.azure.com/
@language=ko
@detectOrientation=false

# POST https://sfmi-vision.cognitiveservices.azure.com/vision/v2.0/ocr?language=ko&detectOrientation=false   HTTP/1.1

POST https://sfmi-vision.cognitiveservices.azure.com/vision/v2.0/ocr?language=ko&detectOrientation=false   HTTP/1.1
Host: sfmi-vision.cognitiveservices.azure.com
Content-Type: application/json
Ocp-Apim-Subscription-Key: 10836b08a9b94acdb129b0cbc6bdbffe

{"url":"https://i0.wp.com/autopostkorea.com/wp-content/uploads/2020/07/2-20.jpg"}
###
